{
    env: {
        PATH: "echo $PWD/node_modules/.bin:$PATH"
    },
    targets: {
        'build/main.js': {
            dependencies: ['src/*.ts'],
            run: "esbuild src/main.ts --outdir=build --bundle --sourcemap --platform=node --format=cjs --external:obsidian --external:electron"
        },
        'build/package.json': {
            dependencies: ['package.json', 'makefile.json5'],
            run: "cat package.json | jq -r '. * .deploy * {deploy:null} | with_entries(select(.value |. != null))' > build/package.json"
        },
        'build/manifest.json': {
            dependencies: ['manifest.json', 'package.json'],
            run: "cat manifest.json | jq -r '.' > build/manifest.json"
        },
        'build/styles.css': {
            dependencies: ['styles.css'],
            run: "cp styles.css build/styles.css"
        },

        // phony

        clean: {
            phony: true,
            run: "rm -rf build node_modules *lock* *yarn* *pnpm*"
        },

        install: {
            phony: true,
            run: [
                "mkdir -p \"$vault_dir/.obsidian/plugins/\"",
                "cp -r $PWD/build \"$vault_dir/.obsidian/plugins/$(cat package.json | jq -r '.name')\""
            ]
        }
    }
}
